# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  subvolOpts = [
    "compress=zstd:1"
    "noatime"
    "ssd"
    "discard=async"
    "space_cache=v2"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0861bfbf-12a9-4e95-8e90-064c61e9723a";
    fsType = "btrfs";
    options = [ "subvol=@" ] ++ subvolOpts;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0861bfbf-12a9-4e95-8e90-064c61e9723a";
    fsType = "btrfs";
    options = [ "subvol=@nix" ] ++ subvolOpts;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/0861bfbf-12a9-4e95-8e90-064c61e9723a";
    fsType = "btrfs";
    options = [ "subvol=@log" ] ++ subvolOpts;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0861bfbf-12a9-4e95-8e90-064c61e9723a";
    fsType = "btrfs";
    options = [ "subvol=@home" ] ++ subvolOpts;
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/0861bfbf-12a9-4e95-8e90-064c61e9723a";
    fsType = "btrfs";
    options = [ "subvol=@cache" ] ++ subvolOpts;
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/0861bfbf-12a9-4e95-8e90-064c61e9723a";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ] ++ subvolOpts;
  };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/0861bfbf-12a9-4e95-8e90-064c61e9723a";
    fsType = "btrfs";
    options = [ "subvol=@docker" ] ++ subvolOpts;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3693-B3EE";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
