{
  imports = [
    ./alacritty.nix
    ./cli-tools.nix
    ./home-style.nix
    ./htop.nix
    ./firefox.nix
    ./kitty.nix
    ./mako.nix
    ./nvim.nix
    ./starship.nix
    ./sway.nix
    ./swaylock.nix
    ./tmux.nix
    ./tofi.nix
    ./utils.nix
    ./zsh.nix
    ./ssh.nix
    ./gpg.nix
    ./git.nix
    ./gammastep.nix
    ./waybar.nix
    ./vscode.nix
    ./nh.nix
    ./xdg.nix
  ];
}
